# Generated by Django 3.1.1 on 2020-11-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsys_tracer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='cluster_id',
            field=models.IntegerField(default=0),
        ),
    ]
